# Generated by Django 6.0.5 on 2026-05-08 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bucket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=100)),
                ('tip_na_cveke', models.CharField(max_length=100)),
                ('golemina', models.CharField(choices=[('mal', 'Мал'), ('sreden', 'Среден'), ('golem', 'Голем')], max_length=10)),
                ('cena', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fotografija', models.ImageField(blank=True, null=True, upload_to='buketi/')),
                ('godina_na_podgotovka', models.IntegerField()),
                ('sveze', models.BooleanField(default=True)),
                ('dali_e_od_EU', models.BooleanField(default=False)),
            ],
        ),
    ]
