# Generated by Django 6.0.5 on 2026-05-08 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bucket',
            new_name='Buket',
        ),
    ]
